
package com.example.strider.ui.theme

import androidx.compose.ui.graphics.Color

// LIGHT THEME
val primaryLight = Color(0xFF9FEDF6)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFF9FEDF6)
val onPrimaryContainerLight = Color(0xFF000000)
val secondaryLight = Color(0xFF191E66)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF191E66)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF000000)

// DARK THEME
val primaryDark = Color(0xFF191E66)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF191E66)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFF9FEDF6)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFF9FEDF6)
val onSecondaryContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF000000)
val onSurfaceDark = Color(0xFFFFFFFF)

// OTHER
val tertiaryLight = Color(0xFF514AC6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6B64E0)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val surfaceVariantLight = Color(0xFFD5E6E5)
val onSurfaceVariantLight = Color(0xFF3A4A49)
val outlineLight = Color(0xFF6A7A7A)
val outlineVariantLight = Color(0xFFB9CAC9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF3F0EF)
val inversePrimaryLight = Color(0xFF00DDDD)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val gradientPrimaryColor = listOf(Color.Blue, Color.Cyan)
val gradientSecondaryColor = listOf(Color.Magenta, Color.Cyan)